[pytest]
testpaths = tests
addopts = -ra --strict-markers --cov=app --cov-report=term-missing --cov-report=xml:reports/evidencias/pruebas-unitarias/coverage.xml --cov-report=html:htmlcov --cov-fail-under=80 --junitxml=reports/evidencias/pruebas-unitarias/junit.xml
