sonar.projectKey=redsolidaria
sonar.projectName=RedSolidaria
sonar.projectVersion=2.0
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=reports/evidencias/pruebas-unitarias/coverage.xml
sonar.exclusions=htmlcov/**,reports/**
sonar.coverage.exclusions=app/__init__.py,app/routers/__init__.py
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

